---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: _data/links.yml
  label: Links
- type: document
  path: _data/menu.yml
  label: Menu
- type: document
  path: _data/keywords.yml
  label: Keywords
- type: document
  path: _data/colors.yml
  label: Colors
- type: directory
  path: _docs
  label: Docs
  create: all
  match: "**/*"
  templates:
  - default
- type: jekyll-pages
  label: Pages
  create: all
  templates:
  - default
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
  publish_command: bundle exec jekyll build -d _site
  preview_env:
  - JEKYLL_ENV=staging
  publish_env:
  - JEKYLL_ENV=production
  preview_output_directory: _site
  output_directory: _site
